import dataclasses
from typing import Optional

from .coach import Coach


@dataclasses.dataclass
class Recipe:
    """A recipe generated by fridGPT"""
    dishName: str
    dishDescription: str
    ingredients: str
    steps: list[str]
    coach: Optional[Coach] = None

    def as_dict(self) -> dict:
        return dataclasses.asdict(self)
